# Generated by Django 3.2.6 on 2021-09-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=50)),
                ('number_of_plants', models.IntegerField(max_length=50)),
                ('number_of_sensors', models.IntegerField(max_length=50)),
                ('planted_area', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_resource', models.CharField(max_length=50)),
                ('water_flow', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='webuser',
            old_name='id',
            new_name='user_id',
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(max_length=50)),
                ('moistuer_level', models.IntegerField(max_length=50)),
                ('sensor_status', models.BooleanField(default=False)),
                ('FK_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS_APP.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='FK_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS_APP.webuser'),
        ),
    ]
