# Generated by Django 3.2.6 on 2021-09-06 13:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0003_auto_20210906_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulewater',
            name='FK_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SIS_APP.webuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
