# Generated by Django 3.2.6 on 2021-09-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0004_auto_20210906_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('weather_report', models.CharField(max_length=30)),
                ('wind_speed', models.FloatField()),
                ('time_zone', models.CharField(max_length=100)),
                ('FK_weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS_APP.webuser')),
            ],
        ),
    ]
