# Generated by Django 3.2.6 on 2021-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0005_weatherapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherapi',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
