# Generated by Django 3.2.7 on 2021-09-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0006_weatherapi_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='contact',
            field=models.CharField(default=1122, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webuser',
            name='farm_name',
            field=models.CharField(default=1122, max_length=50),
            preserve_default=False,
        ),
    ]
