# Generated by Django 4.0.3 on 2022-05-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0008_webuser_recovery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='recovery_code',
            field=models.CharField(max_length=6),
        ),
    ]
