# Generated by Django 4.0.3 on 2022-06-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0009_alter_webuser_recovery_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='lname',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='webuser',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
