# Generated by Django 4.0.3 on 2022-06-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0010_webuser_lname_alter_webuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherapi',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='weatherapi',
            name='feels_like',
        ),
        migrations.RemoveField(
            model_name='weatherapi',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weatherapi',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weatherapi',
            name='time_zone',
        ),
        migrations.RemoveField(
            model_name='weatherapi',
            name='weather_report',
        ),
        migrations.RemoveField(
            model_name='weatherapi',
            name='wind_speed',
        ),
    ]
