# Generated by Django 4.0.3 on 2022-06-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0011_remove_weatherapi_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='city',
            field=models.CharField(default=1111, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WeatherAPI',
        ),
    ]
