# Generated by Django 4.0.3 on 2022-06-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0012_webuser_city_delete_weatherapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='FK_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIS_APP.webuser'),
        ),
    ]
