# Generated by Django 4.0.3 on 2022-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0013_alter_sensor_fk_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensorID',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
