# Generated by Django 4.0.3 on 2022-06-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0015_rename_sensorid_sensor_sensorkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_status',
        ),
        migrations.AddField(
            model_name='sensor',
            name='plant_name',
            field=models.CharField(default=1133, max_length=50),
            preserve_default=False,
        ),
    ]
