# Generated by Django 4.0.3 on 2022-06-11 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0016_remove_sensor_sensor_status_sensor_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='moistuer_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
