# Generated by Django 4.0.3 on 2022-06-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0018_webuser_pump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulewater',
            name='FK_schedule',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
        migrations.DeleteModel(
            name='ScheduleWater',
        ),
    ]
