# Generated by Django 4.0.3 on 2022-06-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0019_remove_schedulewater_fk_schedule_delete_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='moistuer_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='plant_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensorkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='contact',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='farm_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='pump',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='recovery_code',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
