# Generated by Django 4.0.3 on 2022-06-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIS_APP', '0020_alter_sensor_moistuer_level_alter_sensor_plant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='farm_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='pump',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='recovery_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
